version: '3.8'
services:
  archguard-frontend:
    image: "archguard/archguard-frontend:latest"
    container_name: archguard-frontend
    depends_on:
      - archguard-backend
    ports:
      - "11080:80"
    networks:
      - dependence_network

  archguard-backend:
    image: "archguard/archguard-backend:latest"
    container_name: archguard-backend
    depends_on:
      archguard_flyway:
        condition: service_started
      archguard_mysql:
        condition: service_healthy
    environment:
      app_env: debug
    volumes:
      - "~/.m2:/root/.m2"
      - "~/.gradle:/root/.gradle"
    healthcheck:
      test: curl -f http://localhost:8080/api/actuator/health || exit 1
      timeout: 10s
      retries: 5
    networks:
      - dependence_network
    restart: on-failure:10

  archguard_mysql:
    image: "mysql:8"
    container_name: archguard_mysql
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: archguard
      TZ: Asia/Shanghai
    networks:
      - dependence_network
    volumes:
      - ./archguard_mysql:/var/lib/mysql:rw
#    user: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

  flyway:
    container_name: archguard_flyway
    image: "flyway/flyway:7.15.0"
    command:
      -locations=/flyway/sql -connectRetries=60 migrate
    environment:
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=prisma
      - FLYWAY_URL=jdbc:mysql://archguard_mysql:3306/archguard
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - archguard_mysql
    networks:
      - dependence_network

  archguard_influxdb:
    image: "influxdb:1.8"
    container_name: archguard_influxdb
    ports:
      - '8086:8086'
    networks:
      - dependence_network
    healthcheck:
      test: curl -f http://localhost:8086/ping || exit 1
      timeout: 10s
      retries: 5
    volumes:
      - ./archguard_influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

networks:
  dependence_network:
