name: Publish package to GitHub Packages

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        assets:
          - scan_git/build/libs/scan*-all.jar
          - scan_jacoco/build/libs/scan*-all.jar
          - scan_sourcecode/build/libs/scan*-all.jar
          - scan_test_badsmell/build/libs/scan*-all.jar
          - diff_changes/build/libs/diff_changes*-all.jar
          - analyser_sca/build/libs/analyser_sca*-all.jar
          - analyser_sourcecode/feat_apicalls/build/libs/feat*-all.jar
          - analyser_sourcecode/feat_datamap/build/libs/feat*-all.jar
          - analyser_sourcecode/lang_csharp/build/libs/lang*-all.jar
          - analyser_sourcecode/lang_golang/build/libs/lang*-all.jar
          - analyser_sourcecode/lang_java/build/libs/lang*-all.jar
          - analyser_sourcecode/lang_kotlin/build/libs/lang*-all.jar
          - analyser_sourcecode/lang_python/build/libs/lang*-all.jar
          - analyser_sourcecode/lang_scala/build/libs/lang*-all.jar
          - analyser_sourcecode/lang_typescript/build/libs/lang*-all.jar
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload asserts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.assets }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
