name: Publish to DockerHub

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        assets:
          # analysers:
          - analyser_diff_changes/build/libs/analyser_diff_changes*-all.jar
          - analyser_git/build/libs/analyser_git*-all.jar
          - analyser_sca/build/libs/analyser_sca*-all.jar
          - analyser_sourcecode/feat_apicalls/build/libs/feat_apicalls*-all.jar
          - analyser_sourcecode/feat_datamap/build/libs/feat_datamap*-all.jar
          - analyser_sourcecode/lang_csharp/build/libs/lang_csharp*-all.jar
          - analyser_sourcecode/lang_golang/build/libs/lang_golang*-all.jar
          - analyser_sourcecode/lang_java/build/libs/lang_java*-all.jar
          - analyser_sourcecode/lang_kotlin/build/libs/lang_kotlin*-all.jar
          - analyser_sourcecode/lang_python/build/libs/lang_python*-all.jar
          - analyser_sourcecode/lang_scala/build/libs/lang_scala*-all.jar
          - analyser_sourcecode/lang_typescript/build/libs/lang_typescript*-all.jar
          # cli:
          - scanner_cli/build/libs/scanner_cli*-all.jar
          # rules:
          - rule-linter/rule-sql/build/libs/rule-sql*.jar
          - rule-linter/rule-webapi/build/libs/rule-webapi*.jar
          - rule-linter/rule-test-code/build/libs/rule-test-code*.jar
          # server:
          - server/build/libs/server*.jar

    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build -x test

      - name: Upload assets to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.assets }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

#      - name: Log in to Docker Hub
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: archguard/archguard-backend
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
